import { Badge, Person, Plan, Chat, Message, ConfirmedMeeting } from '../types';

export const badges: Badge[] = [
  { id: 'cinema', label: 'Ходит в кино', icon: '🎬', category: 'interests' },
  { id: 'coffee', label: 'Любит кофейни', icon: '☕', category: 'interests' },
  { id: 'evening', label: 'Активен вечером', icon: '🌙', category: 'time' },
  { id: 'spontaneous', label: 'Спонтанные планы', icon: '⚡', category: 'lifestyle' },
  { id: 'travel', label: 'Часто путешествует', icon: '✈️', category: 'interests' },
  { id: 'art', label: 'Любит выставки', icon: '🎨', category: 'interests' },
  { id: 'music', label: 'Ходит на концерты', icon: '🎵', category: 'interests' },
  { id: 'sports', label: 'Спортивный досуг', icon: '⚽', category: 'interests' },
  { id: 'foodie', label: 'Любит рестораны', icon: '🍽️', category: 'interests' },
  { id: 'morning', label: 'Утренняя активность', icon: '🌅', category: 'time' },
  { id: 'weekend', label: 'Активен на выходных', icon: '🎉', category: 'time' },
  { id: 'local', label: 'Локальные места', icon: '📍', category: 'lifestyle' },
  { id: 'verified', label: 'Верифицирован T-ID', icon: '✓', category: 'verified' },
];

export const mockPeople: Person[] = [
  {
    id: '1',
    name: 'Аня',
    age: 27,
    photo: 'https://images.unsplash.com/photo-1734764627105-b5ff03f02b2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    photos: [
      'https://images.unsplash.com/photo-1734764627105-b5ff03f02b2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
      'https://images.unsplash.com/photo-1755261424887-d428d5b53782?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
      'https://images.unsplash.com/photo-1609091289242-735df7a2207a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ],
    badges: [badges[0], badges[1], badges[2], badges[3], badges[12]],
    verified: true,
    distance: '2 км',
    bio: 'Любит кофе и вечерние прогулки',
    about: 'Обожаю кино и уютные кофейни. По вечерам люблю гулять по центру города. Открыта к спонтанным планам!',
  },
  {
    id: '2',
    name: 'Дмитрий',
    age: 28,
    photo: 'https://images.unsplash.com/photo-1695485121912-25c7ea05119c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    photos: [
      'https://images.unsplash.com/photo-1695485121912-25c7ea05119c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
      'https://images.unsplash.com/photo-1616235931343-10a92ecaeaf2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ],
    badges: [badges[5], badges[6], badges[2], badges[8], badges[12]],
    verified: true,
    distance: '3 км',
    bio: 'Ценитель искусства и хорошей музыки',
    about: 'Люблю ходить на выставки и концерты. Предпочитаю интересные беседы в хороших ресторанах.',
  },
  {
    id: '3',
    name: 'Мария',
    age: 24,
    photo: 'https://images.unsplash.com/photo-1699903905361-4d408679753f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    photos: [
      'https://images.unsplash.com/photo-1699903905361-4d408679753f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ],
    badges: [badges[0], badges[5], badges[2], badges[11], badges[12]],
    verified: true,
    distance: '1.5 км',
    bio: 'Любитель кино и локальных мест',
    about: 'Предпочитаю небольшие уютные места большим мероприятиям. Ищу компанию для походов в кино и на выставки.',
  },
  {
    id: '4',
    name: 'Александр',
    age: 29,
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ],
    badges: [badges[7], badges[8], badges[10], badges[3], badges[12]],
    verified: true,
    distance: '4 км',
    bio: 'Активный образ жизни и хорошая еда',
    about: 'Люблю активный досуг и пробовать новые рестораны. По выходным часто выбираюсь на спортивные мероприятия.',
  },
  {
    id: '5',
    name: 'Екатерина',
    age: 25,
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    photos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ],
    badges: [badges[1], badges[4], badges[9], badges[11], badges[12]],
    verified: true,
    distance: '2.5 км',
    bio: 'Путешествия и утренний кофе',
    about: 'Люблю путешествовать и открывать новые места. По утрам предпочитаю начинать день с хорошего кофе.',
  },
  {
    id: '6',
    name: 'Максим',
    age: 27,
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    photos: [
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ],
    badges: [badges[6], badges[0], badges[2], badges[10], badges[12]],
    verified: true,
    distance: '3.5 км',
    bio: 'Музыка и кино - моя страсть',
    about: 'Регулярно хожу на концерты и в кино. По выходным люблю активный отдых с друзьями.',
  },
  {
    id: '7',
    name: 'София',
    age: 26,
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    photos: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ],
    badges: [badges[1], badges[5], badges[2], badges[3], badges[12]],
    verified: true,
    distance: '1 км',
    bio: 'Искусство и спонтанность',
    about: 'Люблю спонтанные планы и творческие мероприятия. Ищу единомышленников для интересных встреч.',
  },
  {
    id: '8',
    name: 'Артём',
    age: 30,
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    photos: [
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ],
    badges: [badges[8], badges[4], badges[10], badges[3], badges[12]],
    verified: true,
    distance: '5 км',
    bio: 'Гастрономия и путешествия',
    about: 'Увлекаюсь кулинарией и люблю открывать новые рестораны. Часто путешествую по выходным.',
  },
];

export const mockPlans: Plan[] = [
  {
    id: '1',
    title: 'Балет «Щелкунчик»',
    category: 'event',
    image: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    date: '31 декабря',
    time: '19:00',
    location: 'Большой театр',
    participants: 12,
    maxParticipants: 20,
    description: 'Классическая постановка балета Чайковского. Погрузитесь в атмосферу новогодней сказки.',
    price: 'от 2500 ₽',
    cashback: '10% кэшбэк',
    tags: ['культура', 'классика', 'вечер'],
    interestedPeople: [mockPeople[0], mockPeople[2], mockPeople[4]],
    isPairActivity: true,
  },
  {
    id: '2',
    title: 'Кофе в центре',
    category: 'casual',
    image: 'https://images.unsplash.com/photo-1604881988758-f76ad2f7aac1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    date: 'Сегодня',
    time: '18:00-21:00',
    location: 'Кофейня на Никольской',
    participants: 3,
    description: 'Неспешная беседа за чашкой кофе. Уютное место с хорошей атмосферой.',
    price: '~500 ₽',
    cashback: '5% кэшбэк',
    tags: ['casual', 'вечер', 'общение'],
    interestedPeople: [mockPeople[0], mockPeople[4]],
    isCustom: true,
    isPairActivity: true,
  },
  {
    id: '3',
    title: 'Ужин в ресторане',
    category: 'casual',
    image: 'https://images.unsplash.com/photo-1742593236678-c102b724c102?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    date: 'Сегодня',
    time: '20:00',
    location: 'Ресторан на Тверской',
    participants: 2,
    description: 'Романтический ужин в уютной атмосфере. Попробуем авторскую кухню.',
    price: '~2000 ₽',
    cashback: '15% кэшбэк',
    tags: ['еда', 'вечер', 'романтика'],
    interestedPeople: [mockPeople[1], mockPeople[6]],
    isCustom: true,
    isPairActivity: true,
  },
  {
    id: '4',
    title: 'Кино: новый фильм',
    category: 'activity',
    image: 'https://images.unsplash.com/photo-1739433437912-cca661ba902f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    date: 'Завтра',
    time: '19:30',
    location: 'Каро 11 Октябрь',
    participants: 4,
    description: 'Смотрим новинку кино, после можем обсудить за чашкой кофе.',
    price: '600 ₽',
    cashback: '5% кэшбэк',
    tags: ['кино', 'вечер', 'развлечение'],
    interestedPeople: [mockPeople[0], mockPeople[2], mockPeople[5]],
    isPairActivity: true,
  },
  {
    id: '5',
    title: 'Прогулка по парку',
    category: 'casual',
    image: 'https://images.unsplash.com/photo-1564947879483-2c9f372f0aca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    date: 'Завтра',
    time: '14:00',
    location: 'Парк Горького',
    participants: 2,
    description: 'Неспешная прогулка на свежем воздухе. Можно покататься на велосипедах.',
    tags: ['прогулка', 'день', 'природа'],
    interestedPeople: [mockPeople[3], mockPeople[6]],
    isCustom: true,
    isPairActivity: true,
  },
  {
    id: '6',
    title: 'Концерт Димы Билана',
    category: 'event',
    image: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    date: '5 января',
    time: '20:00',
    location: 'Крокус Сити Холл',
    participants: 8,
    maxParticipants: 15,
    description: 'Большой сольный концерт с новой программой.',
    price: 'от 3000 ₽',
    cashback: '15% кэшбэк',
    tags: ['музыка', 'концерт', 'вечер'],
    interestedPeople: [mockPeople[1], mockPeople[5]],
  },
  {
    id: '7',
    title: 'Прогулка по Арбату',
    category: 'casual',
    date: 'Завтра',
    time: '15:00',
    location: 'Старый Арбат',
    participants: 5,
    description: 'Прогулка по историческому центру с остановкой в уютных местах.',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    tags: ['прогулка', 'день', 'casual'],
    interestedPeople: [mockPeople[2], mockPeople[3], mockPeople[4]],
    isCustom: true,
    isPairActivity: true,
  },
  {
    id: '8',
    title: 'Выставка современного искусства',
    category: 'activity',
    image: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    date: '3 января',
    time: '12:00',
    location: 'Гараж',
    participants: 6,
    maxParticipants: 10,
    description: 'Новая выставка современных художников. Обсудим впечатления после.',
    price: '600 ₽',
    cashback: '10% кэшбэк',
    tags: ['искусство', 'культура', 'день'],
    interestedPeople: [mockPeople[1], mockPeople[2]],
    isPairActivity: true,
  },
  {
    id: '9',
    title: 'Ужин в новом ресторане',
    category: 'casual',
    date: 'Сегодня',
    time: '20:00',
    location: 'White Rabbit',
    participants: 2,
    maxParticipants: 4,
    description: 'Попробуем новое меню и разделим счет. Панорамный вид на город.',
    price: '~3000 ₽',
    cashback: '20% кэшбэк',
    tags: ['еда', 'вечер', 'премиум'],
    interestedPeople: [mockPeople[3]],
    isCustom: true,
    isPairActivity: true,
  },
  {
    id: '10',
    title: 'Каток в Парке Горького',
    category: 'activity',
    date: 'Завтра',
    time: '17:00',
    location: 'Парк Горького',
    participants: 4,
    description: 'Покатаемся на коньках и выпьем глинтвейн.',
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    price: '800 ₽',
    tags: ['спорт', 'зима', 'активность'],
    interestedPeople: [mockPeople[0], mockPeople[6]],
    isCustom: true,
    isPairActivity: true,
  },
];

// Добавляем совместимость к людям для конкретных планов
mockPlans[0].interestedPeople[0].compatibility = 94;
mockPlans[0].interestedPeople[0].compatibilityReasons = [
  'Вы оба часто ходите на культурные мероприятия',
  'Оба активны вечером после 19:00',
  'Схожий ритм жизни и предпочтения',
];

mockPlans[0].interestedPeople[1].compatibility = 88;
mockPlans[0].interestedPeople[1].compatibilityReasons = [
  'Вы оба любите искусство и выставки',
  'Предпочитаете локальные интересные места',
  'Схожий темп активности',
];

mockPlans[1].interestedPeople[0].compatibility = 92;
mockPlans[1].interestedPeople[0].compatibilityReasons = [
  'Вы оба любите кофейни',
  'Предпочитаете спонтанные встречи',
  'Активны в вечернее время',
];

mockPlans[2].interestedPeople[0].compatibility = 85;
mockPlans[2].interestedPeople[0].compatibilityReasons = [
  'Вы оба ходите на концерты',
  'Схожий формат досуга',
  'Активны на выходных',
];

export const mockCurrentUser: Person = {
  id: 'me',
  name: 'Вы',
  age: 27,
  photo: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400',
  badges: [badges[0], badges[1], badges[2], badges[3], badges[5], badges[12]],
  verified: true,
};

const now = new Date();

export const mockChats: Chat[] = [
  {
    id: '1',
    person: mockPeople[0],
    plan: mockPlans[0],
    messages: [
      {
        id: '1',
        senderId: mockPeople[0].id,
        text: 'Привет! Тоже хочешь на Щелкунчика? 🎭',
        timestamp: new Date(now.getTime() - 3600000),
        read: true,
      },
      {
        id: '2',
        senderId: 'me',
        text: 'Да! Давно хотел посмотреть эту постановку',
        timestamp: new Date(now.getTime() - 3000000),
        read: true,
      },
      {
        id: '3',
        senderId: mockPeople[0].id,
        text: 'Отлично! Может встретимся у входа за 15 минут?',
        timestamp: new Date(now.getTime() - 1800000),
        read: true,
      },
      {
        id: '4',
        senderId: 'me',
        text: 'Звучит отлично! До встречи',
        timestamp: new Date(now.getTime() - 900000),
        read: true,
      },
    ],
    unreadCount: 0,
  },
  {
    id: '2',
    person: mockPeople[1],
    plan: mockPlans[2],
    messages: [
      {
        id: '5',
        senderId: mockPeople[1].id,
        text: 'Привет! Идешь на концерт?',
        timestamp: new Date(now.getTime() - 600000),
        read: false,
      },
    ],
    unreadCount: 1,
  },
];

mockChats[0].lastMessage = mockChats[0].messages[mockChats[0].messages.length - 1];
mockChats[1].lastMessage = mockChats[1].messages[mockChats[1].messages.length - 1];

export const mockConfirmedMeetings: ConfirmedMeeting[] = [
  {
    id: '1',
    plan: mockPlans[1], // Coffee
    person: mockPeople[0], // Аня
    date: 'Сегодня',
    time: '19:12',
    status: 'confirmed',
    isToday: true,
  },
  {
    id: '2',
    plan: mockPlans[3], // Прогулка
    person: mockPeople[2], // Мария
    date: 'Завтра',
    time: '15:00',
    status: 'confirmed',
    isToday: false,
  },
];